/*
 * Copyright (c) 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Dagger (https://dagger.dev).
package dev.chromeos.videocompositionsample.data.repository;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class TestCaseRepo_Factory implements Factory<TestCaseRepo> {
  @Override
  public TestCaseRepo get() {
    return newInstance();
  }

  public static TestCaseRepo_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static TestCaseRepo newInstance() {
    return new TestCaseRepo();
  }

  private static final class InstanceHolder {
    private static final TestCaseRepo_Factory INSTANCE = new TestCaseRepo_Factory();
  }
}
